services:
  ollama:
    image: ollama/ollama:latest  # Use the latest Ollama image
    build:
      context: .  # Ensure this path includes start_ollama.sh in the context
    command: /bin/sh /app/start_ollama.sh  # Use the start_ollama.sh script to start Ollama
    ports:
      - "11434:11434"  # Expose Ollama's communication port for Streamlit
    restart: unless-stopped

  streamlit:
    build: .  # Build the Streamlit container from Dockerfile
    ports:
      - "8501:8501"  # Expose the Streamlit port
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Point Streamlit to Ollama service
    depends_on:
      - ollama  # Ensure Ollama is up before Streamlit starts
    restart: unless-stopped
    entrypoint: ["ollama:11434", "--", "streamlit", "run", "src/QuizCraft.py"]
