tunnel: quizcraft-tunnel
credentials-file: /home/nima/.cloudflared/02cc3178-54b0-4abb-8913-fb17ded9f614.json

ingress:
  - hostname: quizcraft.shafie.org
    service: http://localhost:80
  - service: http_status:404
